
spring:
  application:
    name: mscliente
    
server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      instance:
       instance-id: ${spring.application.name}